management:
    endpoints:
        web:
            exposure:
                include: "*"
---
spring:
    config:
        activate:
            on-profile: default
    web.resources.static-locations: "file:./app"
cds:
    security.mock.users:
    - name: rose
      password: rose
    - name: martha
      password: martha
      roles:
        - reviewer
    - name: amy
      password: amy
      roles:
        - processor
    - name: admin
      password: admin
      roles:
      - admin

    odata-v4:
        endpoint:
            path: "/"

server:
    port: 4004

---
spring:
    config:
        activate:
            on-profile: cloud
cds:
    odata-v4:
        endpoint:
            path: "/"

---
spring:
    config:
        activate:
            on-profile: devtools
    devtools:
        remote:
            secret: capjavarocks
        restart:
            trigger-file: devtools.trigger
#cds.security.openUnrestrictedEndpoints: true
---
spring:
    config:
        activate:
            on-profile: devtools-remote
    devtools:
        remote:
            secret: capjavarocks
cds.security.openUnrestrictedEndpoints: true